version: '3'

services:
  flask_app:
    build: .
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge